name: Webhook Pipeline
# workflow triggers
on:
  repository_dispatch:
    types: [ push, pull_request ]
# build process
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
  
    - run: |
        ls -la
        echo "Hello World"
